# Generated by Django 4.0.1 on 2022-02-23 12:07

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pureapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pure',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='lastname', unique=True),
        ),
        migrations.AlterField(
            model_name='pure',
            name='id',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
    ]
